# Generated by Django 4.2 on 2025-09-07 21:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0009_Auto_BigAuto_TimeZone_Django42"),
        ("reports", "0009_alter_savedreport_filters"),
    ]

    operations = []
