from django.conf import settings

DATETIME_FORMAT = settings.DATETIME_FORMAT
DATE_FORMAT = settings.DATE_FORMAT
TIME_FORMAT = settings.TIME_FORMAT
DATE_INPUT_FORMATS = settings.DATE_INPUT_FORMATS
DATETIME_INPUT_FORMATS = settings.DATETIME_INPUT_FORMATS
TIME_INPUT_FORMATS = settings.TIME_INPUT_FORMATS

# JavaScript formats
MOMENT_DATE_DATA_FMT = settings.MOMENT_DATE_DATA_FMT
MOMENT_DATE_FMT = settings.MOMENT_DATE_FMT
MOMENT_DATETIME_FMT = settings.MOMENT_DATETIME_FMT
FLATPICKR_DATE_FMT = settings.FLATPICKR_DATE_FMT
FLATPICKR_DATETIME_FMT = settings.FLATPICKR_DATETIME_FMT
DATERANGEPICKER_DATE_FMT = settings.DATERANGEPICKER_DATE_FMT

