# Generated by Django 4.2 on 2026-09-19 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('faults', '0015_v4_0_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fault',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='fault',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='faults_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='fault',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='fault',
            name='modified_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='faults_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AlterField(
            model_name='faultreviewinstance',
            name='reviewed_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='faults_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed by'),
        ),
        migrations.AlterField(
            model_name='faulttype',
            name='slug',
            field=models.SlugField(editable=False, help_text='Unique URL friendly identifier made of lowercase characters, dashes, and underscores.', max_length=255, unique=True, verbose_name='Slug'),
        ),
    ]
