# Generated by Django 4.2 on 2026-09-19 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('faults', '0016_alter_fault_created_alter_fault_created_by_and_more'),
        ('parts', '0019_alter_part_is_obsolete'),
        ('service_log', '0028_v4_0_final'),
        ('qa', '0060_v4_0_final'),
        ('attachments', '0010_v4_0_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='fault',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faults.fault', verbose_name='Fault'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parts.part', verbose_name='Part'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='serviceevent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service_log.serviceevent', verbose_name='Service Event'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qa.test', verbose_name='Test'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='testinstance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qa.testinstance', verbose_name='Test Instance'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='testlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qa.testlist', verbose_name='Test List'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='testlistcycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qa.testlistcycle', verbose_name='Test List Cycle'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='testlistinstance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qa.testlistinstance', verbose_name='Test List Instance'),
        ),
    ]
