# Generated by Django 3.2 on 2025-05-07 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0019_auto_20210323_1324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['number'], 'verbose_name': 'unit', 'verbose_name_plural': 'units'},
        ),
    ]
