# Generated by Django 4.2 on 2025-09-07 21:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("units", "0020_Auto_BigAuto_TimeZone_Django42"),
        ("units", "0020_alter_unit_options"),
    ]

    operations = []
