# Generated by Django 4.2 on 2025-09-07 21:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("parts", "0017_Auto_BigAuto_TimeZone_Django42"),
        ("parts", "0017_alter_contact_phone_number"),
    ]

    operations = []
