# Generated by Django 4.2.30 on 2026-09-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parts", "0018_v4_0_final"),
    ]

    operations = [
        migrations.AlterField(
            model_name="part",
            name="is_obsolete",
            field=models.BooleanField(
                default=False,
                help_text="Is this part now obsolete?",
                verbose_name="Is obsolete",
            ),
        ),
    ]
