# Generated by Django 4.2 on 2026-08-10 02:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("qa", "0060_v4_0_final"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testinstance",
            name="work_completed",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                help_text="Format YYYY-MM-DD hh:mm (hh:mm is 24h time e.g. 2012-05-31 14:30)",
            ),
        ),
    ]
